name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.eusousantos.com.br
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /paroquiasmg.com.br/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
